rapidjson - Pull in upstream patch
Currently the build fails with:
```
In file included from /home/damian/OpenCPN/model/src/ais_decoder.cpp:52:
/home/damian/OpenCPN/build-android-arm64/_deps/rapidjson_src-src/include/rapidjson/document.h:319:82: error: cannot assign to non-static data member 'length' with const-qualified type 'const SizeType' (aka 'const unsigned int')
  319 |     GenericStringRef& operator=(const GenericStringRef& rhs) { s = rhs.s; length = rhs.length; }
      |                                                                           ~~~~~~ ^
/home/damian/OpenCPN/build-android-arm64/_deps/rapidjson_src-src/include/rapidjson/document.h:325:20: note: non-static data member 'length' declared const here
  325 |     const SizeType length; //!< length of the string (excluding the trailing NULL terminator)
      |     ~~~~~~~~~~~~~~~^~~~~~
1 error generated.
```

This operator was removed upstream (https://github.com/Tencent/rapidjson/issues/718), pull that in as a patch file, since there is no newer release.